In [64]:
import numpy as np
piles = [3,6,7,11]
h = 8
n = np.array(piles)
p=n-.001
print(n)
for i in range(1,max(n)+2):
    t=(np.rint(p//i)).astype(int)
    if(len(t)+sum(t) == h):
        print('---',end='')
    print(t,i,len(t)+sum(t))

[ 3  6  7 11]
[ 2  5  6 10] 1 27
[1 2 3 5] 2 15
[0 1 2 3] 3 10
---[0 1 1 2] 4 8
---[0 1 1 2] 5 8
[0 0 1 1] 6 6
[0 0 0 1] 7 5
[0 0 0 1] 8 5
[0 0 0 1] 9 5
[0 0 0 1] 10 5
[0 0 0 0] 11 4
[0 0 0 0] 12 4


In [69]:
import numpy as np
piles = [312884470]
h = 312884469
n = np.array(piles)
p=n-.001
print(n)
for i in range(1,10):
    t=(p//i).astype(int)
    if(len(t)+sum(t) == h):
        print('---',end='')
    print(t,i,len(t)+sum(t))

[312884470]
[312884469] 1 312884470
[156442234] 2 156442235
[104294823] 3 104294824
[78221117] 4 78221118
[62576893] 5 62576894
[52147411] 6 52147412
[44697781] 7 44697782
[39110558] 8 39110559
[34764941] 9 34764942


In [2]:
import numpy as np
piles = [1,1,1,10000]
h = 8
n = np.array(piles)
p=n-.001
print(n)
for i in range(1,max(n)+2):
    t=(np.rint(p//i)).astype(int)
    if(len(t)+sum(t) == h):
        print('---',end='')
    print(t,i,len(t)+sum(t))

[    1     1     1 10000]
[   0    0    0 9999] 1 10003
[   0    0    0 4999] 2 5003
[   0    0    0 3333] 3 3337
[   0    0    0 2499] 4 2503
[   0    0    0 1999] 5 2003
[   0    0    0 1666] 6 1670
[   0    0    0 1428] 7 1432
[   0    0    0 1249] 8 1253
[   0    0    0 1111] 9 1115
[  0   0   0 999] 10 1003
[  0   0   0 909] 11 913
[  0   0   0 833] 12 837
[  0   0   0 769] 13 773
[  0   0   0 714] 14 718
[  0   0   0 666] 15 670
[  0   0   0 624] 16 628
[  0   0   0 588] 17 592
[  0   0   0 555] 18 559
[  0   0   0 526] 19 530
[  0   0   0 499] 20 503
[  0   0   0 476] 21 480
[  0   0   0 454] 22 458
[  0   0   0 434] 23 438
[  0   0   0 416] 24 420
[  0   0   0 399] 25 403
[  0   0   0 384] 26 388
[  0   0   0 370] 27 374
[  0   0   0 357] 28 361
[  0   0   0 344] 29 348
[  0   0   0 333] 30 337
[  0   0   0 322] 31 326
[  0   0   0 312] 32 316
[  0   0   0 303] 33 307
[  0   0   0 294] 34 298
[  0   0   0 285] 35 289
[  0   0   0 277] 36 281
[  0   0   0 270] 37 274
[  0   0   

In [4]:
piles =[1,1,1,999999999]
h =10

piles = [1,1,1,10000]
h = 10

n = np.array(piles)
p=n-.001
l=1
r=max(n)+2
tl=0
tr=0
tl1=0
tr1=0
while l<r:
# for wer in range(100):
    m=(l+r)//2
    print(l,r,'-',tl,tr,'-',tl1,tr1,'h',h,'s',len(n)+sum((p//m).astype(int)),'m',m)
    if(tl==l and tl1==l and tr==r and tr1==r):
        h=len(n)+sum((p//(r)).astype(int))
        r+=1
    if(len(n)+sum((p//m).astype(int)) == h):
        if(len(n)+sum((p//(m-1)).astype(int)) > h):
            print('up')
            break
        else:
            # while(len(n)+sum((p//(m-1)).astype(int)) == h):
            #       m-=1
            while l<r:
                print('-',l,r,'-',tl,tr,'-',tl1,tr1,'h',h,'s',len(n)+sum((p//m).astype(int)),'m',m)
                m=(l+r)//2
                if(len(n)+sum((p//m).astype(int)) == h):
                    if(len(n)+sum((p//(m-1)).astype(int)) > h):
                        print('down')
                        break
                    else:
                        r=m
                else:
                    l=m
                        
            break
    elif(len(n)+sum((p//m).astype(int)) > h):
        l=m
    else:
        r=m
    tl1=tl
    tr1=tr
    tl=l
    tr=r
print(m,'ans')

1 10002 - 0 0 - 0 0 h 10 s 5 m 5001
1 5001 - 1 5001 - 0 0 h 10 s 7 m 2501
1 2501 - 1 2501 - 1 5001 h 10 s 11 m 1251
1251 2501 - 1251 2501 - 1 2501 h 10 s 9 m 1876
1251 1876 - 1251 1876 - 1251 2501 h 10 s 10 m 1563
- 1251 1876 - 1251 1876 - 1251 2501 h 10 s 10 m 1563
- 1251 1563 - 1251 1876 - 1251 2501 h 10 s 10 m 1563
- 1407 1563 - 1251 1876 - 1251 2501 h 10 s 11 m 1407
- 1407 1485 - 1251 1876 - 1251 2501 h 10 s 10 m 1485
- 1407 1446 - 1251 1876 - 1251 2501 h 10 s 10 m 1446
- 1426 1446 - 1251 1876 - 1251 2501 h 10 s 11 m 1426
- 1426 1436 - 1251 1876 - 1251 2501 h 10 s 10 m 1436
- 1426 1431 - 1251 1876 - 1251 2501 h 10 s 10 m 1431
- 1428 1431 - 1251 1876 - 1251 2501 h 10 s 11 m 1428
down
1429 ans


In [21]:
for i in range(1429,1876+3):
    print(i,len(n)+sum((p//i).astype(int)))

1429 10
1430 10
1431 10
1432 10
1433 10
1434 10
1435 10
1436 10
1437 10
1438 10
1439 10
1440 10
1441 10
1442 10
1443 10
1444 10
1445 10
1446 10
1447 10
1448 10
1449 10
1450 10
1451 10
1452 10
1453 10
1454 10
1455 10
1456 10
1457 10
1458 10
1459 10
1460 10
1461 10
1462 10
1463 10
1464 10
1465 10
1466 10
1467 10
1468 10
1469 10
1470 10
1471 10
1472 10
1473 10
1474 10
1475 10
1476 10
1477 10
1478 10
1479 10
1480 10
1481 10
1482 10
1483 10
1484 10
1485 10
1486 10
1487 10
1488 10
1489 10
1490 10
1491 10
1492 10
1493 10
1494 10
1495 10
1496 10
1497 10
1498 10
1499 10
1500 10
1501 10
1502 10
1503 10
1504 10
1505 10
1506 10
1507 10
1508 10
1509 10
1510 10
1511 10
1512 10
1513 10
1514 10
1515 10
1516 10
1517 10
1518 10
1519 10
1520 10
1521 10
1522 10
1523 10
1524 10
1525 10
1526 10
1527 10
1528 10
1529 10
1530 10
1531 10
1532 10
1533 10
1534 10
1535 10
1536 10
1537 10
1538 10
1539 10
1540 10
1541 10
1542 10
1543 10
1544 10
1545 10
1546 10
1547 10
1548 10
1549 10
1550 10
1551 10
1552 10
1553 10


In [18]:
len(n)+sum((p//1876).astype(int))

9